blank_issues_enabled: false
contact_links:
  - name: Task
    url: https://github.com/AutomonScript/ams-lang/issues/new?template=task.md
    about: A defined task need to be done on project

  - name: Feature Suggestion
    url: https://github.com/AutomonScript/ams-lang/issues/new?template=feature.md
    about: Suggest a new feature or enhancement

  - name: Bug Report
    url: https://github.com/AutomonScript/ams-lang/issues/new?template=bug.md
    about: Report a reproducible bug or unexpected behavior

  - name: Documentation Request
    url: https://github.com/AutomonScript/ams-lang/issues/new?template=documentation.md
    about: Request improvements or additions to documentation

  - name: Help
    url: https://github.com/AutomonScript/ams-lang/issues/new?template=help.md
    about: Ask for guidance or troubleshooting help

  - name: Others
    url: https://github.com/AutomonScript/ams-lang/issues/new?template=others.md
    about: Anything else that doesn’t fit above